### ISSUE TITLE
Update eslint-config-ts-react peer dependency eslint-plugin-simple-import-sort to support 8.x

### ISSUE THREAD

**Issue by tomislav-s** [acolorbright/acb-tools-and-configs#66]
Hi ACB devs! ❤️ 

I'm using `@acolorbright/eslint-config-ts-react` and `"eslint-plugin-simple-import-sort": "7.x",` is listed as one of its peer dependencies.

I would like to update `eslint-plugin-simple-import-sort` to 8.0.0 but this causes a warning to be logged due to mismatched versions.

Is it possible to update `@acolorbright/eslint-config-ts-react` to support 8.0.0 as well?

**Comment by iksi** [comment]
👋🏻 @tomislav-s,  a new version has been released: https://www.npmjs.com/package/@acolorbright/eslint-config-react/v/3.0.2

**Comment by tomislav-s** [comment]
Thanks a lot @iksi ! Can confirm it works.

Closing issue
