### ISSUE TITLE
Update eslint-config-ts-react peer dependency eslint-plugin-simple-import-sort to support 10.x 

### ISSUE THREAD

**Issue by tomislav-s** [acolorbright/acb-tools-and-configs#79]
Hey ACB devs ❤️ 

It's me again with a similar request 😄 

I would like to update `eslint-plugin-simple-import-sort` to 10.x but it requires updating the peer dependencies of `eslint-config-ts-react`.

Is it possible to update this?

Thanks in advance 🙏

**Comment by iksi** [comment]
@tomislav-s Sorry for the delay, it was kind of busy 😄 This is now available with `@acolorbright/eslint-config-ts-react@3.1.0`
